[Users]
names           = Stefan, Tamara


[Settings]
languageKey     = en
debug           = False


[Room:LivingRoom]
tasks           = Hoover, Mop, Dust, DampDust, CleanWindows, Declutter, PlantWatering

[Room:Office]
tasks           = Hoover, Mop, Dust, DampDust, CleanWindows, Declutter, PlantWatering

[Room:Bedroom]
tasks           = Hoover, Mop, Dust, DampDust, CleanWindows, Declutter, PlantWatering, ChangingBed

[Room:Kitchen]
tasks           = Hoover, Mop, Dust, DampDust, CleanWindows, CleanSink, CleanOven, CleaningFridge, TakeOutTrash, Declutter

[Room:Bathroom]
tasks           = Hoover, Mop, Dust, DampDust, CleanWindows, CleanMirrors, CleanShower, CleanSink, TakeOutTrash, Declutter

[Room:Toilet]
tasks           = Hoover, Mop, Dust, DampDust, CleanWindows, CleanMirrors, CleanToilet, CleanSink, TakeOutTrash, Declutter, PlantWatering

[Room:Hallway]
tasks           = Hoover, Mop, Dust, DampDust

[Room:LaundryRoom]
tasks           = Washing, Washing_60


[Task:Hoover]
name            = Hoover
repeat          = 3     
description     = Hoover the room

[Task:Mop]
name            = Mop
repeat          = 7      
description     = Mopping the floor

[Task:Dust]
name            = Dust
repeat          = 7    
description     = Dusting the room

[Task:Washing]
name            = Washing
repeat          = 7    
description     = Washing the clothes

[Task:Washing_60]
name            = Washing at 60°
repeat          = 14    
description     = Washing at 60° 

[Task:CleanWindows]
name            = Clean Windows
repeat          = 28    
description     = Clean the windows

[Task:CleanMirrors]
name            = Clean Mirrors
repeat          = 7    
description     = Clean the mirrors

[Task:CleanShower]
name            = Clean Shower
repeat          = 7     
description     = Clean the shower

[Task:CleanToilet]
name            = Clean Toilet
repeat          = 7         
description     = Clean the toilet

[Task:CleanSink]
name            = Clean Sink
repeat          = 7         
description     = Clean the sink

[Task:CleanOven]
name            = Clean Oven
repeat          = 14         
description     = Clean the oven

[Task:CleaningFridge]
name            = Clean Fridge
repeat          = 7         
description     = Clean the fridge

[Task:DampDust]
name            = Damp Dust
repeat          = 28                   
description     = Damp dusting the room

[Task:TakeOutTrash]
name            = Take Out Trash
repeat          = 7         
description     = Take out the trash

[Task:Declutter]
name            = Declutter
repeat          = 28
description     = Decluttering

[Task:PlantWatering]
name            = Plant Watering
repeat          = 14
description     = Watering the plants

[Task:ChangingBed]
name            = Changing Bed
repeat          = 14
description     = Changing the bed